### ISSUE TITLE
New clients not being persisted

### ISSUE THREAD

**Issue by xaviershay** [cavalle/banksimplistic#2]
Thanks so much for this project, it's really helped me get my head around this pattern.

I run up a server and start the event bus (btw - be nice to have the event bus rake task in the README). I create new clients, but they don't persist attributes properly:

```
> ClientReport.all.each {|x| puts x.inspect }
#<ClientReport:3 name=nil city=nil uid=nil>
#<ClientReport:4 name=nil city=nil uid=nil>
#<ClientReport:5 name=nil city=nil uid=nil>
#<ClientReport:1 name=nil city=nil uid=nil>
#<ClientReport:2 name=nil city=nil uid=nil>
 => ["3", "4", "5", "1", "2"] 
```

This is also reflected in the test failures:

```
Failures:

  1) Create client In order to start selling other services
  As a banker
  I want to sign up new clients New user sign up
     Failure/Error: click_button "Create client!"
     ActionView::Template::Error:
       No route matches {:action=>"destroy", :controller=>"clients"}
     # ./app/views/clients/index.html.erb:13:in `block in _app_views_clients_index_html_erb___1869135361368763010_2166995120_383953378302977591'
     # ./app/views/clients/index.html.erb:9:in `_app_views_clients_index_html_erb___1869135361368763010_2166995120_383953378302977591'
     # <internal:prelude>:10:in `synchronize'
     # ./spec/acceptance/acceptance_helper.rb:25:in `block in <top (required)>'
     # ./spec/acceptance/create_client_spec.rb:19:in `block (2 levels) in <top (required)>'

  2) Feature name In order to do evil thing with their money
  As a banker
  I want clients to open accounts Client opens a new account
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `accounts' for nil:NilClass
     # ./app/reports/client_details_report.rb:31:in `block in <class:ClientDetailsReport>'
     # ./app/infrastructure/event_handler.rb:7:in `call'
     # ./app/infrastructure/event_handler.rb:7:in `block (2 levels) in on'
     # ./app/infrastructure/event_bus.rb:62:in `call'
     # ./app/infrastructure/event_bus.rb:62:in `block (3 levels) in start'
     # ./app/infrastructure/event_bus.rb:61:in `block (2 levels) in start'
     # ./app/infrastructure/event_bus.rb:58:in `start'
     # ./app/infrastructure/event_bus.rb:4:in `start'
     # ./spec/acceptance/acceptance_helper.rb:12:in `block (3 levels) in <top (required)>'

  3) Send Money Transfer In order for money to circulate  
  As a banker
  I want my clients to send money transfers to other accounts Send money transfer to an internal account
     Failure/Error: page.should have_content "Balance: $0"
       expected #has_content?("Balance: $0") to return true, got false
     # ./spec/acceptance/send_money_transfer_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 3.21 seconds
11 examples, 3 failures
```

(the top one is a result of trying to render a client with a nil uid, which should never happen)

Perhaps this is a version issue with redis/ruby redis library? I don't really know anything about it. I have redis v2.0.4.

**Comment by cavalle** [comment]
I need to investigate this. I don't have any problem and I also have redis v2.0.4. Could you please try switching to other event_bus implementation (`InProcessEventBus`, `AMQPEventBus` (you'll need rabbit) or `ZeroMQEventBus`) in `config/initializers/infrastructure.rb` and let me know if it works for you?

**Comment by xaviershay** [comment]
`InProcessEventBus` works.

**Comment by cavalle** [comment]
I believe this is related to YAML serialization in `app/infrastructure/event.rb` and accessing to the deserialized data hash using symbols as keys (e.g. `app/reports/client_report.rb:9`). This should be trivial to fix but I'd like to reproduce the problem before. I've tried with ruby 1.9.2-p180, ruby-1.8.7-p334 and ree-1.8.7-2011.03 and it always works for me.

Probably switching to JSON serialization or using some Redis feature would make sense here.
